import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
   "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]
[env]
TERM = "alacritty"

[window]
opacity = 0.9

[font]
normal = { family = "JetBrains Mono Nerd Font Mono", style = "medium" }
